### ISSUE TITLE
RQLFilterParsingError when using nested "function-style" logical operators

### ISSUE THREAD

**Issue by mgilski** [cloudblue/django-rql#52]
Hi, I came across this problem when testing:

This works fine (i.e. is parsed without errors)
```python
SomeFilter(qs).apply_filters("phone=1&(phone=1|phone=1)")
```

This raises `RQLFilterParsingError`
```python
SomeFilter(qs).apply_filters("and(phone=1,or(phone=1,phone=1))")
```

\
\
This also doesn't work for some reason
```python
SomeFilter(qs).apply_filters("phone=1|phone=1")
```

But this does
```python
SomeFilter(qs).apply_filters("(phone=1|phone=1)")
```

I'm using Python 3.10.5, django-rql 4.2.0, and Django 4.0.6 (might be this, because it's unsupported according to your docs)

**Comment by maxipavlovic** [comment]
Hi @mgilski, thx for the feedback.

1. `SomeFilter(qs).apply_filters("and(phone=1,or(phone=1,phone=1))")` is the existing grammar limitation. There is an intention to rewrite it sometime, but it's a complex task, which I am never able to find time for :)

2. `SomeFilter(qs).apply_filters("phone=1|phone=1")` - this does not work by design, but I don't really remember the origination of this idea (maybe it's related to the grammar as well).

**Comment by d3rky** [comment]
Fixed: https://github.com/cloudblue/django-rql/pull/53
